name: "distributed_laravel_vue"

services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./backend-laravel:/var/www/app/backend
      - ./frontend-vue:/var/www/app/frontend
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    container_name: "nginx_service"

  frontend:
    build:
      context: ./frontend-vue
      dockerfile: _docker/Dockerfile
    depends_on:
      - backend
    container_name: "frontend_service"

  backend:
    build:
      context: ./backend-laravel
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./backend-laravel:/var/www/app/backend
    depends_on:
      - db
    container_name: "backend_service"

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: "db_service"

volumes:
  dbdata:




